import type { Env } from "./types";
import { parseBasicAuth, sha256Hex } from "./auth";
import { r2Key, type ResolvedRepo } from "./config";
import {
  basename,
  classifyPath,
  type Resource,
  resourceGroupId,
  resourceVersion,
} from "./coordinates";
import {
  type Account,
  accountOwnsGroup,
  authenticate,
  insertAudit,
  ownedPrefixes,
  recordArtifact,
} from "./db";
import { contentTypeFor, textResponse } from "./http";

function unauthorized(): Response {
  return textResponse(401, "Unauthorized", {
    "WWW-Authenticate": 'Basic realm="maven", charset="UTF-8"',
  });
}

/** A snapshot version must go to a snapshot repo and vice-versa; group metadata fits both. */
function repoMatchesResource(repo: ResolvedRepo["repo"], resource: Resource): boolean {
  const version = resourceVersion(resource);
  if (version === null) return true;
  const isSnapshot = version.endsWith("-SNAPSHOT");
  return repo === "snapshot" ? isSnapshot : !isSnapshot;
}

/** Resources we generate ourselves and therefore accept-and-discard on upload. */
function isGenerated(resource: Resource): boolean {
  return (
    resource.kind === "checksum" ||
    resource.kind === "group-metadata" ||
    resource.kind === "snapshot-metadata"
  );
}

async function authenticateRequest(request: Request, env: Env): Promise<Account | null> {
  const creds = parseBasicAuth(request.headers.get("Authorization"));
  if (creds === null) return null;
  const keyHash = await sha256Hex(creds.password);
  return authenticate(env.DB, creds.username, keyHash, Date.now());
}

/** Handle an authenticated deploy (`PUT`). */
export async function handlePut(
  request: Request,
  env: Env,
  resolved: ResolvedRepo,
): Promise<Response> {
  const account = await authenticateRequest(request, env);
  if (account === null) return unauthorized();

  const resource = classifyPath(resolved.relPath);
  if (resource === null) return textResponse(400, "Invalid repository path");

  const groupId = resourceGroupId(resource);
  const prefixes = await ownedPrefixes(env.DB, account.id);
  if (!accountOwnsGroup(prefixes, groupId)) {
    return textResponse(403, `Account '${account.name}' does not own namespace '${groupId}'`);
  }

  if (!repoMatchesResource(resolved.repo, resource)) {
    return textResponse(400, `Version does not match the ${resolved.repo} repository`);
  }

  // Metadata + checksums are generated by us; accept and discard the client's copy.
  if (isGenerated(resource)) return textResponse(200, "OK");

  const key = r2Key(resolved);

  // Releases are immutable: artifacts and signatures cannot be overwritten.
  if (resolved.repo === "release" && (await env.BUCKET.head(key)) !== null) {
    return textResponse(409, "Release artifacts are immutable");
  }

  const body = request.body ?? new Uint8Array();
  await env.BUCKET.put(key, body, {
    httpMetadata: { contentType: contentTypeFor(basename(resolved.relPath)) },
  });

  if (resource.kind === "artifact") {
    await recordArtifact(env.DB, {
      key,
      accountId: account.id,
      repo: resolved.repo,
      groupId: resource.coord.groupId,
      artifactId: resource.coord.artifactId,
      version: resource.coord.version,
      filename: resource.coord.filename,
      extension: resource.coord.extension,
      classifier: resource.coord.classifier,
      // Visible on deploy; signature gating (M3) flips this to start hidden for releases.
      verified: 1,
      deployedAt: Date.now(),
    });
  }

  await insertAudit(
    env.DB,
    account.id,
    "PUT",
    key,
    Date.now(),
    request.headers.get("CF-Connecting-IP"),
  );
  return textResponse(201, "Created");
}
